config/routes.rb
Rails.application.routes.draw do
  root 'slacks#index'
  resources :slacks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/slack.rb
class Slack < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/slacks_controller.rb
class SlacksController < ApplicationController
  before_action :set_slack, only: [:show, :edit, :update, :destroy]

  # GET /slacks
  def index
    @slacks = Slack.all
  end

  # GET /slacks/1
  def show
  end

  # GET /slacks/new
  def new
    @slack = Slack.new
  end

  # GET /slacks/1/edit
  def edit
  end

  # POST /slacks
  def create
    @slack = Slack.new(slack_params)

    if @slack.save
      redirect_to @slack, notice: 'Slack was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /slacks/1
  def update
    if @slack.update(slack_params)
      redirect_to @slack, notice: 'Slack was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /slacks/1
  def destroy
    @slack.destroy
    redirect_to slacks_url, notice: 'Slack was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slack
      @slack = Slack.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def slack_params
      params.require(:slack).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackbotApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/slacks/_form.html.erb
<%= form_with(model: slack, local: true) do |form| %>
  <% if slack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slack.errors.count, "error") %> prohibited this slack from being saved:</h2>

      <ul>
      <% slack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slacks/edit.html.erb
<h1>Editing Slack</h1>

<%= render 'form', slack: @slack %>

<%= link_to 'Show', @slack %> |
<%= link_to 'Back', slacks_path %>

app/views/slacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slacks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slacks.each do |slack| %>
      <tr>
        <td><%= slack.title %></td>
        <td><%= slack.content %></td>
        <td><%= link_to 'Show', slack %></td>
        <td><%= link_to 'Edit', edit_slack_path(slack) %></td>
        <td><%= link_to 'Destroy', slack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slack', new_slack_path %>

app/views/slacks/new.html.erb
<h1>New Slack</h1>

<%= render 'form', slack: @slack %>

<%= link_to 'Back', slacks_path %>

app/views/slacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @slack.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @slack.content %>
</p>

<%= link_to 'Edit', edit_slack_path(@slack) %> |
<%= link_to 'Back', slacks_path %>